source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 2.0'

#network
pod 'RestKit', '~> 0.24.0'

#ui
pod 'MBProgressHUD', '~> 0.9.1'

pod 'TWMessageBarManager'